version: '3.8'

services:
  postgresql:
    build: ./apps/backend/backend/database/postgresql
    image: postgres
    container_name: postgresql
    restart: on-failure
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  backend:
    build: ./apps/backend/
    image: backend
    container_name: backend
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3001:3001
      - 5555:5555
    networks:
      - transcendence
    depends_on:
      - postgresql

  frontend:
    build: ./apps/frontend/
    image: frontend
    container_name: frontend
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - transcendence
    depends_on:
      - backend

networks:
  transcendence:
    driver: bridge
