version: '3.8'

services:
  postgresql:
      build: ./database/postgresql
      image: postgres
      container_name: postgresql
      restart: on-failure
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      # init : true
      networks:
        - transcendence
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"

networks:
  transcendence:
    driver: bridge